#server:
#  servlet:
#    session:
#      timeout: 30m
#
#spring:
#  session:
#    jdbc:
#      table-name: SPRING_SESSION
#
#  datasource:
#    url: jdbc:h2:mem:sessions
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa
#  h2:
#    console:
#      enabled: true

auth-facade:
  url: localhost:8080
auth-properties:
  endpoints: /api/close-session




spring:
  security:
    user:
      name: sa
      password: sa
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      database: 0
      host: localhost
      port: 16379
      #username:
      password: mypass
      timeout: 60000